import Head from "next/head";
import * as React from "react";
import { styled } from "@mui/material/styles";
import Box from "@mui/material/Box";
import Paper from "@mui/material/Paper";
import Grid from "@mui/material/Grid";
import LeftBar from "../components/LeftBar";
import RightBar from "../components/RightBar";
import Feed from "../components/Feed";

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === "dark" ? "#1A2027" : "#fff",
  ...theme.typography.body2,
  padding: theme.spacing(2),
  textAlign: "center",
  color: theme.palette.text.secondary,
}));

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/facebook.svg" />
      </Head>

      <Box sx={{ width: "100%", padding: "20px", background: "#F0F2F5" }}>
        <Grid container columnSpacing={{ xs: 1, sm: 2, md: 3 }}>
          <Grid
            item
            sx={{
              display: { md: "none", xs: "none", sm: "none", lg: "block" },
            }}
            lg={3.5}
          >
            <Item><LeftBar/></Item>
          </Grid>
          <Grid item xs={12} md={8} lg={5}>
            <Feed />
          </Grid>
          <Grid
            item
            md={4}
            lg={3.5}
            sx={{
              display: { md: "block", xs: "none", sm: "none", lg: "block" },
            }}
          >
            <Item><RightBar/></Item>
          </Grid>
        </Grid>
      </Box>
    </div>
  );
}
